
public class Main_2_finally {
    public static void AAmain(String[] args){
    
        /*
     try {
     
     String s = null;
     System.out.println(s.length());
     
     }
    
     catch(NullPointerException x){
         
     System.out.println("s bos nasil uzunlugu olsun?");
     }
     
     finally{
     System.out.println("ben adami sikerim");
     }   
*/




/*
         try {
     
     int[] a = {5,10,15};
     System.out.println(a[5]);
     
     }                                                                      // try daki hatayı catch ile tutamamamıza ragmen finally calisti sonra hemen sistem patladi.
                                                                            // ama tutsaydık finally yine de çalışıcaktı ve sistem patlamayacaktı.
     catch(NullPointerException x){
         
     System.out.println("s bos nasil uzunlugu olsun?");
     }
     
     finally{
     System.out.println("ben adami sikerim");
     } 
*/
    
    
    }
}
